In [32]:
import numpy as np

In [33]:
phi=0
a=[[2,0,0,0,0,0,-1,0,0,-1],[0,2,0,0,0,0,-1,-1,0,0],[0,0,4,0,0,0,0,-1,-1,0],[0,0,0,2*(2**0.5),0,0,0,0,-1,-1],[0,0,0,0,2*(5**0.5),0,-1,0,-1,0],[0,0,0,0,0,0,0,-1,0,-1],[0]*10,[0]*10,[0]*10,[0]*10]

In [34]:
for i in range(len(a)):
    print (len(a[i]))

10
10
10
10
10
10
10
10
10
10


In [35]:
a=np.array(a)

In [36]:
a=a.round(3)

In [37]:
a

array([[ 2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   ,  0.   ,
         0.   , -1.   ],
       [ 0.   ,  2.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   , -1.   ,
         0.   ,  0.   ],
       [ 0.   ,  0.   ,  4.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   ,
        -1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  2.828,  0.   ,  0.   ,  0.   ,  0.   ,
        -1.   , -1.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  4.472,  0.   , -1.   ,  0.   ,
        -1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   ,
         0.   , -1.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ]])

In [38]:
k = np.eye(10)
for i in range (len(a)):
    k[i,i]= a[i,i]

    
        

In [39]:
k

array([[2.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 2.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 4.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 2.828, 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 4.472, 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ]])

In [40]:
a=a-k
a

array([[ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [41]:
k[5,5]=2*(2**0.5)

In [42]:
k=k.round(3)

In [43]:
a=a-a.T
a

array([[ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.],
       [ 1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.]])

In [44]:
a=a+k

In [45]:
a

array([[ 2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   ,  0.   ,
         0.   , -1.   ],
       [ 0.   ,  2.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   , -1.   ,
         0.   ,  0.   ],
       [ 0.   ,  0.   ,  4.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   ,
        -1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  2.828,  0.   ,  0.   ,  0.   ,  0.   ,
        -1.   , -1.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  4.472,  0.   , -1.   ,  0.   ,
        -1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  2.828,  0.   , -1.   ,
         0.   , -1.   ],
       [ 1.   ,  1.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 0.   ,  1.   ,  1.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   ,  1.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 1.   ,  0.   ,  0.   ,  1.   ,  0.   ,  1.   ,  0.   ,  0.   ,
         0.   ,  0.   ]])

In [51]:
phi=0
a[4,5]=phi
a[5,4]=phi

In [52]:
a

array([[ 2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   ,  0.   ,
         0.   , -1.   ],
       [ 0.   ,  2.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   , -1.   ,
         0.   ,  0.   ],
       [ 0.   ,  0.   ,  4.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   ,
        -1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  2.828,  0.   ,  0.   ,  0.   ,  0.   ,
        -1.   , -1.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  4.472,  0.   , -1.   ,  0.   ,
        -1.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  2.828,  0.   , -1.   ,
         0.   , -1.   ],
       [ 1.   ,  1.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 0.   ,  1.   ,  1.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   ,  1.   ,  1.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ],
       [ 1.   ,  0.   ,  0.   ,  1.   ,  0.   ,  1.   ,  0.   ,  0.   ,
         0.   ,  0.   ]])

In [55]:
b=[0]*6+[2]*4
b

[0, 0, 0, 0, 0, 0, 2, 2, 2, 2]

In [56]:
b= np.array(b)

In [57]:
np.linalg.solve(a,b)

array([0.65259915, 0.81101799, 0.65259915, 0.81101799, 0.53638286,
       0.53638286, 0.70517178, 0.91686421, 1.69353237, 0.60002652])

In [82]:
def createa(phi):
    a=[[2,0,0,0,0,0,-1,0,0,-1],[0,2,0,0,0,0,-1,-1,0,0],[0,0,4,0,0,0,0,-1,-1,0],[0,0,0,2*(2**0.5),0,0,0,0,-1,-1],[0,0,0,0,2*(5**0.5),0,-1,0,-1,0],[0,0,0,0,0,0,0,-1,0,-1],[0]*10,[0]*10,[0]*10,[0]*10]
    a=np.array(a)
    #a=a.round(3)
    k = np.eye(10)
    for i in range (len(a)):
        k[i,i]= a[i,i]

    a=a-k
    k[5,5]=2*(2**0.5)
    #k=k.round(3)
    a=a-a.T
    a=a+k
    a[4,5]=phi
    a[5,4]=phi
    return a

In [83]:
def createb():
    b=[0]*6+[2]*4
    b= np.array(b)
    return b

In [84]:
phi=0
a=createa(phi)
b= createb()
np.linalg.solve(a,b)

array([0.65263606, 0.81099212, 0.65263606, 0.81099212, 0.53637182,
       0.53637182, 0.70508387, 0.91690037, 1.69364386, 0.60018825])

In [85]:
phi=5
a=createa(phi)
b= createb()
np.linalg.solve(a,b)

array([0.77236473, 0.95977183, 0.77236473, 0.95977183, 0.26786344,
       0.26786344, 0.68366185, 1.23588182, 1.85357708, 0.86106761])

In [86]:
phi=10
a=createa(phi)
b= createb()
np.linalg.solve(a,b)

array([0.81221032, 1.00928559, 0.81221032, 1.00928559, 0.17850408,
       0.17850408, 0.67653262, 1.34203857, 1.90680272, 0.94788803])

In [87]:
phi=50
a=createa(phi)
b= createb()
np.linalg.solve(a,b)

array([0.87011059, 1.08123483, 0.87011059, 1.08123483, 0.04865458,
       0.04865458, 0.66617302, 1.49629664, 1.98414574, 1.07404817])

In [88]:
phi=100
a=createa(phi)
b= createb()
np.linalg.solve(a,b)

array([0.88044283, 1.09407409, 0.88044283, 1.09407409, 0.02548308,
       0.02548308, 0.66432436, 1.52382381, 1.99794752, 1.0965613 ])

In [89]:
phi=1000
a=createa(phi)
b= createb()
np.linalg.solve(a,b)

array([0.89061876, 1.1067191 , 0.89061876, 1.1067191 , 0.00266214,
       0.00266214, 0.66250367, 1.55093454, 2.01154049, 1.11873384])

In [81]:
phi=10000
a=createa(phi)
b= createb()
np.linalg.solve(a,b).round(7)

array([8.9164290e-01, 1.1080897e+00, 8.9164290e-01, 1.1080897e+00,
       2.6740000e-04, 2.6740000e-04, 6.6237820e-01, 1.5538013e+00,
       2.0127702e+00, 1.1209075e+00])